name: Build Electron Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install desktop deps
        working-directory: desktop-electron
        run: npm ci

      - name: Build Electron (electron-builder)
        working-directory: desktop-electron
        env:
          # Optional: set secrets for code signing
          CSC_LINK: ${{ secrets.CSC_LINK || '' }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD || '' }}
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kgf-electron-windows
          path: desktop-electron/dist/**
